'use client'

import React, { useState, useEffect } from 'react';
import Icon from '../../../components/AppIcon';

const ProblemSection = () => {
  const [currentStat, setCurrentStat] = useState(0);
  const [isVisible, setIsVisible] = useState(false);

  const problemStats = [
    {
      title: "AI Content Growth",
      value: "847%",
      description: "Increase in AI-generated social media posts in 2024",
      icon: "TrendingUp",
      color: "text-black-500"
    },
    {
      title: "Fake Engagement",
      value: "34%",
      description: "Of social media engagement comes from AI-generated content",
      icon: "Users",
      color: "text-black-500"
    },
    {
      title: "Reputation Damage",
      value: "$2.3M",
      description: "Average cost of brand reputation damage from fake content",
      icon: "AlertTriangle",
      color: "text-black-500"
    }
  ];

  const industryExamples = [
    {
      industry: "Journalism",
      problem: "Fake news articles generated by AI spreading misinformation",
      impact: "Loss of credibility and reader trust",
      icon: "Newspaper"
    },
    {
      industry: "Marketing",
      problem: "Competitors using AI to create fake reviews and testimonials",
      impact: "Unfair competitive advantage and consumer deception",
      icon: "Megaphone"
    },
    {
      industry: "Education",
      problem: "Students submitting AI-generated assignments and research",
      impact: "Academic integrity violations and learning gaps",
      icon: "GraduationCap"
    }
  ];

  useEffect(() => {
    const observer = new IntersectionObserver(
      ([entry]) => {
        if (entry.isIntersecting) {
          setIsVisible(true);
        }
      },
      { threshold: 0.1 }
    );

    const element = document.getElementById('problem-section');
    if (element) observer.observe(element);

    return () => observer.disconnect();
  }, []);

  useEffect(() => {
    if (isVisible) {
      const interval = setInterval(() => {
        setCurrentStat((prev) => (prev + 1) % problemStats.length);
      }, 2500);
      return () => clearInterval(interval);
    }
  }, [isVisible]);

  return (
    <section id="problem-section" className="py-20 bg-white">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Section Header */}
        <div className="text-center mb-16">
          <h2 className={`text-4xl md:text-5xl font-bold text-black mb-6 transform transition-all duration-1000 ${isVisible ? 'translate-y-0 opacity-100' : 'translate-y-10 opacity-0'}`}>
            The AI Content Crisis is
            <span className="text-red-500"> Real</span>
          </h2>
          <p className={`text-xl text-gray-700 max-w-3xl mx-auto transform transition-all duration-1000 delay-200 ${isVisible ? 'translate-y-0 opacity-100' : 'translate-y-10 opacity-0'}`}>
            Artificial intelligence is flooding social media with fake content, threatening authenticity and trust across all industries.
          </p>
        </div>

        {/* Animated Statistics */}
        <div className={`grid grid-cols-1 md:grid-cols-3 gap-8 mb-16 transform transition-all duration-1000 delay-400 ${isVisible ? 'translate-y-0 opacity-100' : 'translate-y-10 opacity-0'}`}>
          {problemStats.map((stat, index) => (
            <div
              key={index}
              className={`bg-gray-100 border border-gray-200 rounded-xl p-8 text-center transition-all duration-500 ${
                currentStat === index ? 'scale-105 border-red-500' : 'hover:border-gray-300'
              }`}
            >
              <div className="flex justify-center mb-4">
                <Icon
                  name={stat.icon}
                  size={48}
                  className={`${stat.color} ${currentStat === index ? 'animate-pulse' : ''}`}
                />
              </div>
              <div className={`text-4xl font-bold mb-2 ${stat.color}`}>
                {stat.value}
              </div>
              <h3 className="text-xl font-semibold text-gray-800 mb-2">
                {stat.title}
              </h3>
              <p className="text-gray-600 text-sm">
                {stat.description}
              </p>
            </div>
          ))}
        </div>

        {/* Call to Action */}
        <div className={`text-center mt-16 transform transition-all duration-1000 delay-800 ${isVisible ? 'translate-y-0 opacity-100' : 'translate-y-10 opacity-0'}`}>
          <div className="bg-gray-900 border border-red-200 rounded-2xl p-8 max-w-4xl mx-auto">
            <Icon name="AlertCircle" size={48} className="text-red-500 mx-auto mb-4" />
            <h3 className="text-2xl font-bold text-white mb-4">
              Don't Let AI Content Destroy Your Credibility
            </h3>
            <p className="text-white mb-6">
              Every day you wait, more fake content infiltrates your industry. Take action now to protect your brand's authenticity.
            </p>
            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              <div className="bg-white border border-gray-200 rounded-lg px-6 py-3">
                <div className="text-gray-600 font-bold text-lg">7,392</div>
                <div className="text-gray-600 text-sm">Posts analyzed today</div>
              </div>
              <div className="bg-white border border-gray-200 rounded-lg px-6 py-3">
                <div className="text-gray-600 font-bold text-lg">7,293</div>
                <div className="text-gray-600 text-sm">AI content detected</div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};

export default ProblemSection;
